---
title: "Untitled"
author: "Bo Zhang"
date: "2023-12-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Data Processing
```{r}
library(dplyr)
library(tidyr)
```

# Simulate random variables 
```{r}
set.seed(0)
# Basic, indepedent 
# Sex Income
Sex = rbinom(n = 10000, size = 1, p = 0.48) 
# Age
agesrange <- 50:81
weights <- ifelse(agesrange <= 70, 2.3, 1)
Age <- sample(agesrange, size = 10000, replace = TRUE, prob = weights)
# Income
incomes <- seq(from = 10000, to = 100000, by = 100)
weights <- ifelse(incomes >= 70000, 0.8, 1) 
Income <- sample(incomes, size = 10000, replace = TRUE, prob = weights)

# Stress.Level
Stress.Level<-round(rnorm(10000, mean = (-100+0.08 * Income)/100, sd = 2))
# Exercise.Hours.Per.Week
Exercise.Hours.Per.Week <- numeric(10000)
for(i in 1:10000) {
  base <- 5 
  if(Income[i] > 70000 || Stress.Level[i] < 50) {
    base <- base + 5
  }
  if(Sex[i] == "Female") {
    base <- base - 2
  }
  if(Age[i] > 50) {
    base <- base - 3
  }
  Exercise.Hours.Per.Week[i] <- min(max(round(base + rnorm(1, mean = 0, sd = 10)), 1), 30)
}
# BMI
BMI <- numeric(10000)
for(i in 1:10000) {
  base <- 23
  if(Age[i] > 50) {
    base <- base + 2
  }
  if(Exercise.Hours.Per.Week[i] > 15) {
    base <- base - 2
  }
  if(Sex[i] == "Female") {
    base <- base - 1
  }

  BMI[i] <- round(base + rnorm(1, mean = 0, sd = 2), 1)
}

# Blood.Pressure
Blood.Pressure <- numeric(10000)
for(i in 1:10000) {
  base_systolic <- 120  
  base_diastolic <- 80  
  adj_systolic <- base_systolic + (BMI[i] - 25) + (Age[i] - 50) / 10
  adj_diastolic <- base_diastolic + (BMI[i] - 25) / 2 + (Age[i] - 50) / 20
  Blood.Pressure[i] <- ifelse(130< round(adj_systolic + rnorm(1, mean = 10, sd = 10), 0), 1,0)
}

# Diabetes
Diabetes <- rbinom(10000, size = 1, prob = plogis(-6 + 0.05 * BMI + 0.02 * Age + rnorm(10000, mean = 0.5, sd = 3)))


# Alcohol.Consumption
Alcohol.Consumption <- rbinom(10000, size = 1, prob = plogis(-3 + 0.01 * Stress.Level + 0.03 * Age + rnorm(10000, mean = 0.5, sd = 3)))


# Triglycerides
Triglycerides <- rbinom(10000, size = 1, prob = plogis(-4 + 0.1 * Blood.Pressure + 0.5 * Diabetes +
                                                     0.1 * Alcohol.Consumption + 0.02 * BMI +
                                                     0.01 * Age - 0.01 * Exercise.Hours.Per.Week +
                                                     0.000005 * Income + 0.09 * Stress.Level + 0.3 * Sex +
                                                     rnorm(10000, mean = 0.01, sd = 3)))

# Smoking
Smoking <- rbinom(10000, size = 1, prob = plogis(-5 + 0.1 * Blood.Pressure + 0.1 * Diabetes +
                                                 0.1 * Alcohol.Consumption + 0.05 * BMI +
                                                 0.02 * Age - 0.02 * Exercise.Hours.Per.Week +
                                                 0.00001 * Income + 0.06 * Stress.Level +
                                                 0.2 * Triglycerides + 0.3 * Sex +
                                                 rnorm(10000, mean = 0.01, sd = 1)))


# Heart.Attack.Risk
Heart.Attack <- rbinom(10000, size = 1, prob = plogis(-8+ 2.42 * Smoking -
                                                     0.5 * Sex -
                                                     Smoking * Sex +
                                                     0.3 * Blood.Pressure + 0.6 * Diabetes +
                                                     0.2 * Alcohol.Consumption + 0.03 * BMI +
                                                     0.003 * Age - 0.05 * Exercise.Hours.Per.Week +
                                                     0.000002 * Income + 0.02 * Stress.Level +
                                                     0.4 * Triglycerides +
                                                     rnorm(10000, mean = 0.3, sd = 3)))


# loss_to_follow_up
loss_to_follow_up <- numeric(10000)
for(i in 1:10000) {
  risk <- plogis(-5 + 0.02 * Age[i] + 0.03 * Stress.Level[i] - 0.00001 * Income[i] + 0.04 * BMI[i]+
                  rnorm(1, mean = 0.3, sd = 3))
  loss_to_follow_up[i] <- ifelse(0.99 < risk, 1, 0)
}
sum(loss_to_follow_up)

for(i in 1:10000) {
  if(loss_to_follow_up[i] == 1) {
    Heart.Attack[i] <- NA
  }
}
data <- data.frame(
  Age,
  Sex,
  Exercise.Hours.Per.Week,
  Income,
  Stress.Level,
  BMI,
  Diabetes,
  Blood.Pressure,
  Alcohol.Consumption,
  Triglycerides,
  Smoking,
  Heart.Attack
)
data <- na.omit(data)
head(data, 8)
library(psych)
describe(data)[c('mean', 'sd','min','max', 'skew' )]

library(writexl)
write_xlsx(list(Description = describe(data)), "description.xlsx")
```
```{r}
data_smokers <- transform(data, Smoking = 1)

# 创建非吸烟者数据集
data_nonsmokers <- transform(data, Smoking = 0)

# 定义计算心脏病风险的函数
calculate_heart_attack_risk <- function(data) {
 rbinom(10000, size = 1, prob = plogis(-8+ 2.42 * Smoking -
                                                     0.5 * Sex -
                                                     Smoking * Sex +
                                                     0.3 * Blood.Pressure + 0.6 * Diabetes +
                                                     0.2 * Alcohol.Consumption + 0.03 * BMI +
                                                     0.003 * Age - 0.05 * Exercise.Hours.Per.Week +
                                                     0.000002 * Income + 0.02 * Stress.Level +
                                                     0.4 * Triglycerides +
                                                     rnorm(10000, mean = 0.3, sd = 3)))
}

risk_smokers <- calculate_heart_attack_risk(data_smokers)
risk_nonsmokers <- calculate_heart_attack_risk(data_nonsmokers)

risk_ratio <- sum(risk_smokers) / sum(risk_nonsmokers)
risk_ratio
risk_difference <- (sum(risk_smokers) - sum(risk_nonsmokers))/10000
risk_difference
ATE = mean(risk_smokers - risk_nonsmokers)
ATE

```


```{r}
data <- data[c('Smoking', 'Heart.Attack',"Age", "Sex", "Blood.Pressure", "Diabetes", "BMI", "Alcohol.Consumption", "Exercise.Hours.Per.Week",  "Stress.Level", "Income", "Triglycerides")]
# Assuming 'data' is your DataFrame with the blood pressure readings as "systolic/diastolic"

# Convert 'Diabetes' and 'Alcohol.Consumption' from integers to factors
data$Sex <- as.factor(data$Sex)
data$Diabetes <- as.factor(data$Diabetes)
data$Alcohol.Consumption <- as.factor(data$Alcohol.Consumption)
data$Blood.Pressure <- as.factor(data$Blood.Pressure)
data$Smoking <- as.factor(data$Smoking)
data$Heart.Attack <- as.factor(data$Heart.Attack)
data$Triglycerides <- as.factor(data$Triglycerides)
 

# Convert factors to dummy variables
dummy_data <- data %>%
  mutate(across(where(is.factor), as.numeric))

# Now compute the correlation matrix
cor_matrix <- cor(dummy_data, use = "complete.obs")

# Plot
library(corrplot)
# Visualize the correlation matrix
corrplot(cor_matrix, method = "color", order = "hclust",
         tl.col = "black", tl.srt = 45)
```


```{r}
library(ggplot2)
heart_attack_rates <- data %>%
  group_by(Smoking) %>%
  summarize(IncidenceRate = mean(as.numeric(Heart.Attack)-1))
ggplot(heart_attack_rates, aes(x = factor(Smoking), y = IncidenceRate, fill = factor(Smoking))) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = c("blue", "red")) +
  labs(x = "Smoking Status", y = "Incidence Rate of Heart Disease", fill = "Smoking Status") +
  theme_minimal()
```
# Propensity Score
```{r}
data$Sex <- as.numeric(data$Sex)-1
data$Diabetes <- as.numeric(data$Diabetes)-1
data$Alcohol.Consumption <- as.numeric(data$Alcohol.Consumption)-1
data$Blood.Pressure <- as.numeric(data$Blood.Pressure)-1
data$Smoking <- as.numeric(data$Smoking)-1
data$Heart.Attack <- as.numeric(data$Heart.Attack)-1
logit_model <- glm(Smoking ~  Age + Sex + Blood.Pressure + Diabetes + BMI + Alcohol.Consumption + Exercise.Hours.Per.Week + Stress.Level + Income, family = binomial, data = data)
summary(logit_model)
exp(cbind(OR = coef(logit_model), confint(logit_model)))

# propensity score
propensity_model <- glm(Smoking ~  Age + Sex + Blood.Pressure + Diabetes + BMI + Alcohol.Consumption + Exercise.Hours.Per.Week + Stress.Level + Income + Triglycerides, family = binomial(link ="logit"), data = data) 
data$ps <- predict(propensity_model, type = "response")
# Calculate IPW
data$IPW <- ifelse(data$Smoking == 1, 
                       1/data$ps, 
                       1/(1 - data$ps))

# check balance with IPW using ASD
covariates <- c("Age", "Sex", "Blood.Pressure", "Diabetes", "BMI", "Alcohol.Consumption", "Exercise.Hours.Per.Week",  "Stress.Level", "Income", "Triglycerides")
ASD_val <- sapply(covariates, function(var) {
  if (is.numeric(data[[var]])) {
    # Proceed with calculation for numeric variables
    mean_1 <- weighted.mean(data[data$Smoking == 1, var], w = data[data$Smoking == 1, "IPW"])
    mean_0 <- weighted.mean(data[data$Smoking == 0, var], w = data[data$Smoking == 0, "IPW"])
    sd_1 <- sqrt(var(data[data$Smoking == 1, var]))
    sd_0 <- sqrt(var(data[data$Smoking == 0, var]))
    asd <- abs(mean_1 - mean_0) / sqrt((sd_1^2 + sd_0^2) / 2)
  } else {
    # For factors, compare proportions instead of means
    prop_1 <- sum(data[data$Smoking == 1, var] == 1, na.rm = TRUE) / sum(data$Smoking == 1, na.rm = TRUE)
    prop_0 <- sum(data[data$Smoking == 0, var] == 1, na.rm = TRUE) / sum(data$Smoking == 0, na.rm = TRUE)
    asd <- abs(prop_1 - prop_0) # For binary factors, standard deviation is not required
  }
  return(asd)
})
print(ASD_val) # all good balance
```

```{r}
hist(data$IPW)
# OK
```

```{r}
library(ggplot2)
ggplot(data, aes(x=ps, fill=factor(Smoking))) + 
  geom_histogram(alpha=0.5, position="identity", bins=30) + 
  labs(title="Histogram of Propensity Scores by Smoking", x="Propensity Score", fill="Smoking") + 
  theme_minimal()
```

# Love plot
```{r}
data$OW <- ifelse(data$Smoking ==1,1- data$ps, data$ps)
ASD_val_ori <- sapply(covariates,function(var) { 
   if (is.numeric(data[[var]])) {
  mean_1 <- mean(data[data$Smoking ==1, var]) 
  mean_0 <- mean(data[data$Smoking ==0, var]) 
  sd_1 <- sd(data[data$Smoking ==1, var]) 
  sd_0 <- sd(data[data$Smoking ==0, var]) 
  asd <- abs(mean_1 - mean_0) / sqrt((sd_1^2+ sd_0^2) /2)
   } else {
    # For factors, compare proportions instead of means
    prop_1 <- sum(data[data$Smoking == 1, var] == 1, na.rm = TRUE) / sum(data$Smoking == 1, na.rm = TRUE)
    prop_0 <- sum(data[data$Smoking == 0, var] == 1, na.rm = TRUE) / sum(data$Smoking == 0, na.rm = TRUE)
    asd <- abs(prop_1 - prop_0) # For binary factors, standard deviation is not required
  }
  return(asd)})
ASD_val_IPW <- sapply(covariates,function(var) { 
  if (is.numeric(data[[var]])) {
  mean_1 <- weighted.mean(data[data$Smoking ==1, var], w = data[data$Smoking ==1,"IPW"]) 
  mean_0 <- weighted.mean(data[data$Smoking ==0, var], w = data[data$Smoking ==0,"IPW"]) 
  sd_1 <- sd(data[data$Smoking ==1, var]) 
  sd_0 <- sd(data[data$Smoking ==0, var]) 
  asd <- abs(mean_1 - mean_0) / sqrt((sd_1^2+ sd_0^2) /2)
  } else {
    # For factors, compare proportions instead of means
    prop_1 <- sum(data[data$Smoking == 1, var] == 1, na.rm = TRUE) / sum(data$Smoking == 1, na.rm = TRUE)
    prop_0 <- sum(data[data$Smoking == 0, var] == 1, na.rm = TRUE) / sum(data$Smoking == 0, na.rm = TRUE)
    asd <- abs(prop_1 - prop_0) # For binary factors, standard deviation is not required
  }
  return(asd)})
ASD_val_OW <- sapply(covariates,function(var) {
  if (is.numeric(data[[var]])) {
  mean_1 <- weighted.mean(data[data$Smoking ==1, var], w = data[data$Smoking ==1,"OW"]) 
  mean_0 <- weighted.mean(data[data$Smoking ==0, var], w = data[data$Smoking ==0,"OW"]) 
  sd_1 <- sd(data[data$Smoking ==1, var]) 
  sd_0 <- sd(data[data$Smoking ==0, var]) 
  asd <- abs(mean_1 - mean_0) / sqrt((sd_1^2+ sd_0^2) /2)
} else {
    # For factors, compare proportions instead of means
    prop_1 <- sum(data[data$Smoking == 1, var] == 1, na.rm = TRUE) / sum(data$Smoking == 1, na.rm = TRUE)
    prop_0 <- sum(data[data$Smoking == 0, var] == 1, na.rm = TRUE) / sum(data$Smoking == 0, na.rm = TRUE)
    asd <- abs(prop_1 - prop_0) # For binary factors, standard deviation is not required
  }
  return(asd)})
love_data <- data.frame( 
  Covariate = rep(covariates,3), 
  ASD = c(ASD_val_ori, ASD_val_IPW, ASD_val_OW),
  Method = factor(rep(c("Original","IPW","OW"), 
                      each = length(covariates)), 
                  levels = c("Original","IPW","OW")))
ggplot(love_data, aes(x = ASD, y = Covariate, color = Method)) + 
  geom_point(size =3) + 
  geom_vline(xintercept =0, linetype ="dashed", color ="red") + 
  labs(title ="Love Plot of ASDs", x ="Absolute Standardized Difference", y ="Covariate") + scale_color_brewer(palette ="Set1")
#extreme weight (特别容易在treatment/control中出现)

```
# Exclude 
```{r}
covariates <- c("Age", "Sex", "Blood.Pressure", "Diabetes", "BMI", "Alcohol.Consumption", "Exercise.Hours.Per.Week",  "Stress.Level", "Income")
data$OW <- ifelse(data$Smoking ==1,1- data$ps, data$ps)
ASD_val_ori <- sapply(covariates,function(var) { 
   if (is.numeric(data[[var]])) {
  mean_1 <- mean(data[data$Smoking ==1, var]) 
  mean_0 <- mean(data[data$Smoking ==0, var]) 
  sd_1 <- sd(data[data$Smoking ==1, var]) 
  sd_0 <- sd(data[data$Smoking ==0, var]) 
  asd <- abs(mean_1 - mean_0) / sqrt((sd_1^2+ sd_0^2) /2)
   } else {
    # For factors, compare proportions instead of means
    prop_1 <- sum(data[data$Smoking == 1, var] == 1, na.rm = TRUE) / sum(data$Smoking == 1, na.rm = TRUE)
    prop_0 <- sum(data[data$Smoking == 0, var] == 1, na.rm = TRUE) / sum(data$Smoking == 0, na.rm = TRUE)
    asd <- abs(prop_1 - prop_0) # For binary factors, standard deviation is not required
  }
  return(asd)})
ASD_val_IPW <- sapply(covariates,function(var) { 
  if (is.numeric(data[[var]])) {
  mean_1 <- weighted.mean(data[data$Smoking ==1, var], w = data[data$Smoking ==1,"IPW"]) 
  mean_0 <- weighted.mean(data[data$Smoking ==0, var], w = data[data$Smoking ==0,"IPW"]) 
  sd_1 <- sd(data[data$Smoking ==1, var]) 
  sd_0 <- sd(data[data$Smoking ==0, var]) 
  asd <- abs(mean_1 - mean_0) / sqrt((sd_1^2+ sd_0^2) /2)
  } else {
    # For factors, compare proportions instead of means
    prop_1 <- sum(data[data$Smoking == 1, var] == 1, na.rm = TRUE) / sum(data$Smoking == 1, na.rm = TRUE)
    prop_0 <- sum(data[data$Smoking == 0, var] == 1, na.rm = TRUE) / sum(data$Smoking == 0, na.rm = TRUE)
    asd <- abs(prop_1 - prop_0) # For binary factors, standard deviation is not required
  }
  return(asd)})
ASD_val_OW <- sapply(covariates,function(var) {
  if (is.numeric(data[[var]])) {
  mean_1 <- weighted.mean(data[data$Smoking ==1, var], w = data[data$Smoking ==1,"OW"]) 
  mean_0 <- weighted.mean(data[data$Smoking ==0, var], w = data[data$Smoking ==0,"OW"]) 
  sd_1 <- sd(data[data$Smoking ==1, var]) 
  sd_0 <- sd(data[data$Smoking ==0, var]) 
  asd <- abs(mean_1 - mean_0) / sqrt((sd_1^2+ sd_0^2) /2)
} else {
    # For factors, compare proportions instead of means
    prop_1 <- sum(data[data$Smoking == 1, var] == 1, na.rm = TRUE) / sum(data$Smoking == 1, na.rm = TRUE)
    prop_0 <- sum(data[data$Smoking == 0, var] == 1, na.rm = TRUE) / sum(data$Smoking == 0, na.rm = TRUE)
    asd <- abs(prop_1 - prop_0) # For binary factors, standard deviation is not required
  }
  return(asd)})
ggplot(love_data, aes(x = ASD, y = Covariate, color = Method)) + 
  geom_point(size = 3) + 
  geom_vline(xintercept = 0, linetype = "dashed", color = "red") + 
  labs(title = "Love Plot of ASDs", x = "Absolute Standardized Difference", y = "Covariate") +
  scale_color_brewer(palette = "Set1") +
  theme(axis.text.y = element_text(angle = 45, hjust = 1))

#extreme weight (特别容易在treatment/control中出现)
```


# Table

```{r}
library(gt)
# Calculate means for original data for both treatment groups
orig_mean_group1 <- lapply(covariates, function(v) mean(data[data$Smoking == 1, v]))
orig_mean_group0 <- lapply(covariates, function(v) mean(data[data$Smoking == 0, v]))
# Calculate means using IPW weights for both treatment groups
mean_ipw_group1 <- lapply(covariates, function(v) { 
  weighted.mean(data[data$Smoking == 1, v], 
                data[data$Smoking == 1, "IPW"])
})
mean_ipw_group0 <- lapply(covariates, function(v) {
  weighted.mean(data[data$Smoking == 0, v], 
                data[data$Smoking == 0, "IPW"])
})
# Calculate means using OW weights for both treatment groups
mean_ow_group1 <- lapply(covariates, function(v) { 
  weighted.mean(data[data$Smoking == 1, v], 
                data[data$Smoking == 1, "OW"])
})
mean_ow_group0 <- lapply(covariates, function(v) {
  weighted.mean(data[data$Smoking == 0, v], 
                data[data$Smoking == 0, "OW"])
})
# Aggregate the results
aggregated_results <- data.frame(
  Variable = covariates,
  Original_Mean1 = unlist(orig_mean_group1),
  Weighted_IPW_Mean1 = unlist(mean_ipw_group1),
  Weighted_OW_Mean1 = unlist(mean_ow_group1),
  Original_Mean0 = unlist(orig_mean_group0),
  Weighted_IPW_Mean0 = unlist(mean_ipw_group0),
  Weighted_OW_Mean0 = unlist(mean_ow_group0)
)
# Create a table for display
display_table <- gt(data = aggregated_results) %>%
  tab_header(
    title = "Table 1: Averages by Heart Attack Risk"
  ) %>%
  cols_label(
    Variable = "Variable",
    Original_Mean1 = "Unweighted",
    Weighted_IPW_Mean1 = "IPW Adjusted",
    Weighted_OW_Mean1 = "OW Adjusted",
    Original_Mean0 = "Unweighted",
    Weighted_IPW_Mean0 = "IPW Adjusted",
    Weighted_OW_Mean0 = "OW Adjusted"
  ) %>%
  tab_spanner(
    label = "Heart Attack Risk 1",
    columns = vars(Original_Mean1, Weighted_IPW_Mean1, Weighted_OW_Mean1)
  ) %>%
  tab_spanner(
    label = "Heart Attack Risk 0",
    columns = vars(Original_Mean0, Weighted_IPW_Mean0, Weighted_OW_Mean0)
  )
display_table
```


# risk ratio (RR) with an outcome regression (OR) estimator
```{r}
#bootstrap
# Fit a combined model
fit_combined <- lm(Heart.Attack ~ Smoking + ., data = data)
# Obtain the predicted values for both treatment groups
predicted_values <- predict(fit_combined, newdata = data)
# Extract predictions based on treatment
predicted_Y1_mod <- predicted_values[data$Smoking == 1]
predicted_Y0_mod <- predicted_values[data$Smoking == 0]
# Compute the means for predicted outcomes
mean_Y1_mod <- mean(predicted_Y1_mod)
mean_Y0_mod <- mean(predicted_Y0_mod)
# Risk Difference (RD) and Risk Ratio (RR) calculations
RD_mod <- mean_Y1_mod - mean_Y0_mod
RR_mod <- mean_Y1_mod / mean_Y0_mod
RD_mod
RR_mod
set.seed(123) # For reproducibility n_iterations <- 100
n_data <- nrow(data)
n_iterations <- 1000
# Initialize vectors to store bootstrap estimates
bootstrap_RD <- numeric(n_iterations)
bootstrap_RR <- numeric(n_iterations)
for (i in 1:n_iterations) {
  # Resample data with replacement
  bootstrap_sample <- data[sample(1:n_data, n_data, replace = TRUE), ]
  # Fit the model on bootstrap sample
  fit_combined <- lm(Heart.Attack ~ Smoking + ., data = data)
  predicted_values <- predict(fit_combined, newdata = bootstrap_sample)
  # Extract predictions based on treatment
  predicted_Y1_mod <- predicted_values[bootstrap_sample$Smoking == 1]
  predicted_Y0_mod <- predicted_values[bootstrap_sample$Smoking == 0]
  # Compute RD and RR for bootstrap sample
  bootstrap_RD[i] <- mean(predicted_Y1_mod) - mean(predicted_Y0_mod)
  bootstrap_RR[i] <- mean(predicted_Y1_mod) / mean(predicted_Y0_mod)
}
# Compute the 95% confidence intervals
CI_RD <- quantile(bootstrap_RD, c(0.025, 0.975))
CI_RR <- quantile(bootstrap_RR, c(0.025, 0.975))
CI_RD
CI_RR
```

# RR with propensity score  with estimated propensity scores
```{r}
fit_Y1_c <- lm(Heart.Attack ~ ps, data = data[data$Smoking == 1,])
predicted_Y1_c <- predict(fit_Y1_c, newdata = data)
fit_Y0_c <- lm(Heart.Attack ~ ps, data = data[data$Smoking == 0,])
predicted_Y0_c <- predict(fit_Y0_c, newdata = data)
RD_c <- mean(predicted_Y1_c) - mean(predicted_Y0_c)
RR_c <- mean(predicted_Y1_c) / mean(predicted_Y0_c)
RD_c
RR_c
set.seed(123) # For reproducibility n_iterations <- 100
n_data <- nrow(data)
# Initialize vectors to store bootstrap estimates
bootstrap_RD_c <- numeric(n_iterations)
bootstrap_RR_c <- numeric(n_iterations)
for (i in 1:n_iterations) {
# Resample data with replacement
  bootstrap_sample <- data[sample(1:n_data, n_data, replace = TRUE), ]
  # Fit the models on bootstrap sample for treated group
  fit_Y1_c <- lm(Heart.Attack ~ ps, data = bootstrap_sample[bootstrap_sample$Smoking==1,])
  predicted_Y1_c <- predict(fit_Y1_c, newdata = bootstrap_sample)
  # Fit the models on bootstrap sample for control group
  fit_Y0_c <- lm(Heart.Attack ~ ps, data = bootstrap_sample[bootstrap_sample$Smoking==0,])
  predicted_Y0_c <- predict(fit_Y0_c, newdata = bootstrap_sample)
  # Compute RD and RR for bootstrap sample
  bootstrap_RD_c[i] <- mean(predicted_Y1_c) - mean(predicted_Y0_c)
  bootstrap_RR_c[i] <- mean(predicted_Y1_c) / mean(predicted_Y0_c)
}
# Compute the 95% confidence intervals
CI_RD_c <- quantile(bootstrap_RD_c, c(0.025, 0.975))
CI_RR_c <- quantile(bootstrap_RR_c, c(0.025, 0.975))
CI_RD_c
CI_RR_c
```

# Risk Ratio (RR) with propensity score  with IPW estimator
```{r}
library(PSweight)
formula <- reformulate(covariates, response="Smoking")
data$Heart.Attack <- as.numeric(as.character(data$Heart.Attack))
data$Smoking <- as.numeric(as.character(data$Smoking))
ipw <- PSweight(ps.formula = formula, yname = 'Heart.Attack', data = data, weight = "IPW") # RD:
summary(ipw, type = 'DIF', CI = TRUE)[1]
summary(ipw, type = 'RR', CI=TRUE)[1]
```
# Risk Ratio (RR) with propensity score  with OW estimator
```{r}
ow <- PSweight(ps.formula = formula, yname = 'Heart.Attack', data = data, weight = "overlap") # RD:
print(summary(ow, type = 'DIF', CI=TRUE)[1])
print(summary(ow, type = 'RR', CI=TRUE)[1])
```

# Sensitivity analysis
```{r}
## logistic regression -- obtain the conditional odds ratio
library(EValue)
lead.loglinear = glm(Heart.Attack ~ ., family = binomial(link = "logit"),  data = data)
est_se = summary(lead.loglinear)$coef["Smoking", c(1, 2)]

est      = RR(exp(est_se[1]))
lowerRR  = exp(est_se[1] - 1.96*est_se[2])
upperRR  = exp(est_se[1] + 1.96*est_se[2])
evalue(est, lowerRR, upperRR)

#找or的公式写paper里
#unmeasured confounders
```



```{r}
# Convert 'Diabetes' and 'Alcohol.Consumption' from integers to factors
data$Sex <- as.factor(data$Sex)
data$Diabetes <- as.factor(data$Diabetes)
data$Alcohol.Consumption <- as.factor(data$Alcohol.Consumption)
data$Blood.Pressure <- as.factor(data$Blood.Pressure)
data$Smoking <- as.factor(data$Smoking)
data$Heart.Attack <- as.factor(data$Heart.Attack)
 
# Convert factors to dummy variables
dummy_data <- data %>%
  mutate(across(where(is.factor), as.numeric)) #%>%
 # select(where(is.numeric))

dummy_data$Sex<-dummy_data$Sex-1
dummy_data$Diabetes<-dummy_data$Diabetes-1
dummy_data$Blood.Pressure<-dummy_data$Blood.Pressure-1
dummy_data$Alcohol.Consumption<-dummy_data$Alcohol.Consumption-1
dummy_data$Smoking<-dummy_data$Smoking-1
dummy_data$Heart.Attack<-dummy_data$Heart.Attack-1

library(boot)
num_bootstraps<-100
compute_ate <- function(data,indices) {
  
  # Compute ATE for this bootstrap sample
  subset_data <- data[indices, ]
 ate <- mean(subset_data$Heart.Attack[subset_data$Smoking == 1]) - 
         mean(subset_data$Heart.Attack[subset_data$Smoking == 0])
  
  return(ate)
}

bootstrap_results <- boot(data=dummy_data,statistic = compute_ate, R = num_bootstraps)

# Get standard error of ATE
se_ate <- sd(bootstrap_results$t)
ate_true<-mean(dummy_data$Heart.Attack[dummy_data$Smoking == 1]) - mean(dummy_data$Heart.Attack[dummy_data$Smoking == 0])
ate_true
se_ate

```

```{r direct regression}
direct_reg_model <- lm(Heart.Attack ~ Smoking + Age + Sex + Blood.Pressure + Diabetes + BMI + Alcohol.Consumption + Exercise.Hours.Per.Week + Stress.Level + Income, data = dummy_data)
att_estimate <- coef(direct_reg_model)["Smoking"]
att_estimate
confint(direct_reg_model,level=0.95)
SE_ATE <- summary(direct_reg_model)$coef['Smoking', 'Std. Error']
SE_ATE
```

```{r matching estimator}
library(MatchIt)

# Perform matching
match_obj <- matchit(Smoking ~  Age + Sex + Blood.Pressure + Diabetes + BMI + Alcohol.Consumption + Exercise.Hours.Per.Week + Stress.Level + Income, data = dummy_data, method = "nearest")

# Extract matched data
matched_data <- match.data(match_obj)

# Estimate ATE using linear regression
model <- lm(Heart.Attack ~ Smoking, data = matched_data)

# Extract ATE coefficient
ate <- coef(model)["Smoking"]
ate

# Calculate confidence interval for ATE
ate_ci <- confint(model)["Smoking", ]
ate_ci
```


```{r propensity score calculation: smoking}
#confounders include age/ sex/ diabetes/ blood pressure/ BMI/ alchohol consumption/ stress level/ exercise hours per week/ Income
library(PSweight)
ps.smoking.mult<-Smoking ~  Age + Sex + Blood.Pressure + Diabetes + BMI + Alcohol.Consumption + Exercise.Hours.Per.Week + Stress.Level + Income
#check balance
#bal.smoking.mult <- SumStat(ps.formula = ps.smoking.mult,
#weight = c("IPW", "overlap", "matching", "entropy"), data = dummy_data)
#plot(bal.smoking.mult, type = "density",ylim=c(0,100))
#plot(bal.smoking.mult, metric = "ASD")
#propensity score
#bal.smoking.mult$IPW.sumstat
#bal.smoking.mult$overlap.sumstat
#PStrim(ps.formula = ps.smoking.mult, data = dummy_data, optimal = TRUE)
#ATT estimate
ps_weights_smoking <- PSweight(ps.formula = ps.smoking.mult, data = dummy_data,
weight = "overlap",trtgrp = "1",zname = "Smoking",yname = "Heart.Attack",
bootstrap = TRUE,R = 100)
att_weighting_smoking <- summary(ps_weights_smoking)$estimates["Contrast 1", "Estimate"]
se_att_weighting_smoking <- summary(ps_weights_smoking)$estimates["Contrast 1", "Std.Error"]
att_weighting_smoking 
se_att_weighting_smoking
summary(ps_weights_smoking)$estimates
ps_weights_smoking_ipw <- PSweight(ps.formula = ps.smoking.mult, data = dummy_data,
weight = "IPW",trtgrp = "1",zname = "Smoking",yname = "Heart.Attack",
bootstrap = TRUE,R = 100)
summary(ps_weights_smoking_ipw)$estimates
```


```{r doubly robust estimator:smoking}
###double robust estimator
ps_smoking_formula <- Smoking ~  Age + Sex + Blood.Pressure + Diabetes + BMI + Alcohol.Consumption + Exercise.Hours.Per.Week + Stress.Level + Income
or_smoking_formula <- Heart.Attack ~ Smoking + Age + Sex + Blood.Pressure + Diabetes + BMI + Alcohol.Consumption + Exercise.Hours.Per.Week + Stress.Level + Income
# Use PSweight to estimate ATT using a doubly robust estimator obverlap weights
ps_smoking <- PSweight(ps.formula = ps_smoking_formula, data = dummy_data,
weight = "IPW",trtgrp = "1",zname = "Smoking",yname = "Heart.Attack",out.formula = or_smoking_formula,
bootstrap = TRUE,R = 100)
summary(ps_smoking)
```

```{r machine learning propensity score estimation}
ps.smoking.gbm <- Smoking ~  Age + Sex + Blood.Pressure + Diabetes + BMI + Alcohol.Consumption + Exercise.Hours.Per.Week + Stress.Level + Income
bal.any.gbm <-SumStat(ps.formula = ps.smoking.gbm, data= dummy_data, weight = "overlap",
method = "gbm", ps.control = list(distribution = "adaboost"))
out.smoking.gbm <- Heart.Attack ~ Smoking + Age + Sex + Blood.Pressure + Diabetes + BMI + Alcohol.Consumption + Exercise.Hours.Per.Week + Stress.Level + Income
ato.smoking.aug.gbm <- PSweight(ps.formula = ps.smoking.gbm, data = dummy_data,trtgrp = "1",zname = "Smoking", yname = "Heart.Attack", out.formula = out.smoking.gbm, ps.method = "gbm", ps.control = list(distribution = "adaboost"),out.method = "gbm",bootstrap = TRUE,R = 100)
summary(ato.smoking.aug.gbm)

```


```{r subgroup analysis}
# we separately calculate the ate in different sex groups
ps_subgroup_formula <- Smoking ~  Age + Blood.Pressure + Diabetes + BMI + Alcohol.Consumption + Exercise.Hours.Per.Week + Stress.Level + Income
data0<-dummy_data[dummy_data$Sex == 0,]
data1<-dummy_data[dummy_data$Sex == 1,]
ps_weights_smoking0 <- PSweight(ps.formula = ps_subgroup_formula, data = data0,
weight = "overlap",trtgrp = "1",zname = "Smoking",yname = "Heart.Attack",
bootstrap = TRUE,R = 100)
summary(ps_weights_smoking0)
ps_weights_smoking1 <- PSweight(ps.formula = ps_subgroup_formula, data = data1,
weight = "overlap",trtgrp = "1",zname = "Smoking",yname = "Heart.Attack",
bootstrap = TRUE,R = 100)
summary(ps_weights_smoking1)

```

```{r subgroup analysis by comorbidities in diabetes}
# we separately calculate the ate in diabetes patients
ps_subgroup_formula_d <- Smoking ~  Age + Sex+ Blood.Pressure + BMI + Alcohol.Consumption + Exercise.Hours.Per.Week + Stress.Level + Income
data0d<-dummy_data[dummy_data$Diabetes == 0,]
data1d<-dummy_data[dummy_data$Diabetes == 1,]
ps_weights_d0 <- PSweight(ps.formula = ps_subgroup_formula_d, data = data0d,
weight = "overlap",trtgrp = "1",zname = "Diabetes",yname = "Heart.Attack",
bootstrap = TRUE,R = 100)
summary(ps_weights_d0)
ps_weights_d1 <- PSweight(ps.formula = ps_subgroup_formula_d, data = data1d,
weight = "overlap",trtgrp = "1",zname = "Diabetes",yname = "Heart.Attack",
bootstrap = TRUE,R = 100)
summary(ps_weights_d1)
```

```{r subgroup analysis by comorbidities in hypertension}
# we separately calculate the ate in hypertension patients
ps_subgroup_formula_h <- Smoking ~  Age + Sex+ Diabetes + BMI + Alcohol.Consumption + Exercise.Hours.Per.Week + Stress.Level + Income
data0h<-dummy_data[dummy_data$Blood.Pressure == 0,]
data1h<-dummy_data[dummy_data$Blood.Pressure == 1,]
ps_weights_h0 <- PSweight(ps.formula = ps_subgroup_formula_h, data = data0h,
weight = "overlap",trtgrp = "1",zname = "Blood.Pressure",yname = "Heart.Attack",
bootstrap = TRUE,R = 100)
summary(ps_weights_h0)
ps_weights_h1 <- PSweight(ps.formula = ps_subgroup_formula_h, data = data1h,
weight = "overlap",trtgrp = "1",zname = "Blood.Pressure",yname = "Heart.Attack",
bootstrap = TRUE,R = 100)
summary(ps_weights_h1)
```

